/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssistantMessage: typeof import('./src/components/ChatCore/AssistantMessage.vue')['default']
    BotCard: typeof import('./src/components/BotCard/src/BotCard.vue')['default']
    Button: typeof import('./src/components/Button/src/Button.vue')['default']
    CardSection: typeof import('./src/components/CardSection/index.vue')['default']
    CarouselSection: typeof import('./src/components/CarouselSection/index.vue')['default']
    ChatCore: typeof import('./src/components/ChatCore/index.vue')['default']
    ChatInputCom: typeof import('./src/components/ChatInputCom/index.vue')['default']
    Collect: typeof import('./src/components/MChatInputSection/Collect.vue')['default']
    Copy: typeof import('./src/components/ChatCore/Copy.vue')['default']
    CumButton: typeof import('./src/components/Button/src/CumButton.vue')['default']
    DialogSection: typeof import('./src/components/DialogSection/index.vue')['default']
    Dislike: typeof import('./src/components/ChatCore/Dislike.vue')['default']
    DynamicInputBox: typeof import('./src/components/Button/src/DynamicInputBox.vue')['default']
    FilePreview: typeof import('./src/components/ChatInputCom/FilePreview.vue')['default']
    Form: typeof import('./src/components/Form/src/Form.vue')['default']
    IntroduceSection: typeof import('./src/components/IntroduceSection/index.vue')['default']
    Loading: typeof import('./src/components/ChatCore/Loading.vue')['default']
    MAssistantMessage: typeof import('./src/components/DialogSection/MAssistantMessage.vue')['default']
    MChatInputSection: typeof import('./src/components/MChatInputSection/index.vue')['default']
    MDislike: typeof import('./src/components/DialogSection/MDislike.vue')['default']
    Message: typeof import('./src/components/MsgBox/Message.vue')['default']
    MGuide: typeof import('./src/components/DialogSection/MGuide.vue')['default']
    MUserMessage: typeof import('./src/components/DialogSection/MUserMessage.vue')['default']
    QuestionSection: typeof import('./src/components/QuestionSection/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeechAnimation: typeof import('./src/components/SpeechAnimation/SpeechAnimation.vue')['default']
    StepButton: typeof import('./src/components/Button/src/StepButton.vue')['default']
    TokenWrite: typeof import('./src/components/TokenWrite/src/TokenWrite.vue')['default']
    UserMessage: typeof import('./src/components/ChatCore/UserMessage.vue')['default']
    Voiceing: typeof import('./src/components/MChatInputSection/Voiceing.vue')['default']
  }
}
